const googleSheetsTitles = [
  "The North Man",
  "Apocalypse Now",
  "Clock Work Orange",
  "Blade Runner 2048",
  "All of Us Are Dead",
  "12 Angry Men",
  "The Mad Men",
  "Barry 2018",
  "Your Lie in April",
  "Johnny Bolt",
  "Better Call Saul",
  "Evangelion",
  "Jackass Forever",
  "Everything Everywhere All at Once",
  "Odd Taxi",
  "Airplane",
  "Monty Python",
  "Idiocracy",
  "Spaceballs",
  "The Shining",
  "Smiling Friends",
  "Westworld",
  "One Piece",
  "Disenchantment",
  "Young Justice",
  "That Time I Got Turned Into a Slime",
  "The Promised Neverland",
  "The Rising of the Shield Hero",
  "Goblin Slayer",
  "Tokyo Ghoul:re",
  "Attack on Titan",
  "Seven Deadly Sins",
  "Overlord",
  "JoJo's Bizarre Adventure",
  "Hunter x Hunter",
  "My Hero Academia",
  "Mob Psycho 100",
  "F is for Family",
  "Akame ga Kill",
  "Another",
  "Re:Zero",
  "Parasyte the Maxim",
  "Gurren Lagann",
  "Erased",
  "Log Horizon",
  "Steins Gate 0",
  "Full Metal Alchemist Brotherhood",
  "Angel Beats",
  "Afro Samurai",
  "Mirai Nikki (Future Diary)",
  "Tales of Borderlands",
  "Stranger Things",
  "Brooklyn 99",
  "Insatiable",
  "The Mist",
  "Lord of War",
  "Whiplash",
  "No Country for Old Men",
  "Full Metal Jacket",
  "Jojo Rabbit",
  "1917",
  "Parasyte",
  "Dragon Ball Broly",
  "Goodfellas",
  "Alita: Battle Angel",
  "Silence of the Lambs",
  "Baby Driver",
  "Hardcore Henry",
  "My Honor Was Loyalty",
  "Inglourious Basterds",
  "Incredibles 2",
  "Deadpool 2",
  "Green Mile",
  "Shawshank Redemption",
  "Avengers (All of them)",
  "John Wick 3",
  "Black Mirror",
  "Altered Carbon",
  "Ex Machina",
  "Bridge to Terabithia",
  "Watership Down",
  "Plague Dogs",
  "Leon the Professional",
  "The Shape of Voice",
  "Shaolin Soccer",
  "Groundhog Day",
  "Powder",
  "Southland",
  "Prison School",
  "All Quiet on the Western Front",
  "Oldboy",
  "I Saw the Devil",
  "Chainsaw Man",
  "The Raid: Redemption",
  "M*A*S*H",
  "Blackadder",
  "Hells Parade",
  "Heavenly Delusion",
  "Cyberpunk: Edgerunners",
  "John Wick 4",
  "The Sopranos",
  "Succession",
  "The Day the Earth Stood Still",
  "Super Troopers",
  "Grave of the Fireflies",
  "I Want to Eat Your Pancakes",
  "Higurashi",
  "Superhero Movie",
  "Furiosa: A Mad Max Saga",
  "The Whale",
  "The Shogun",
  "Delicious in Dungeon",
  "Dune",
  "Dune 2",
  "The Office",
  "Star Wars: The Bad Batch",
  "Kaiju No. 8",
  "Frieren at Journey's End",
  "Leon the Professional",
  "Spice and Wolf",
  "VVThe Departed",
  "Bone Tomahawk",
];

const webAppTitles = [
  "The North Man",
  "Apocalypse Now",
  "Clock Work Orange",
  "Blade Runner 2048",
  "All of Us Are Dead",
  "12 Angry Men",
  "The Mad Men",
  "Barry 2018",
  "Your Lie in April",
  "Johnny Bolt",
  "Better Call Saul",
  "Evangelion",
  "Jackass Forever",
  "Everything Everywhere All at Once",
  "Odd Taxi",
  "Airplane",
  "Monty Python",
  "Idiocracy",
  "Spaceballs",
  "The Shining",
  "Smiling Friends",
  "Westworld",
  "One Piece",
  "Disenchantment",
  "Young Justice",
  "That Time I Got Turned Into a Slime",
  "The Promised Neverland",
  "The Rising of the Shield Hero",
  "Goblin Slayer",
  "Tokyo Ghoul:re",
  "Attack on Titan",
  "Seven Deadly Sins",
  "Overlord",
  "JoJo's Bizarre Adventure",
  "Hunter x Hunter",
  "My Hero Academia",
  "Mob Psycho 100",
  "F is for Family",
  "Akame ga Kill",
  "Another",
  "Re:Zero",
  "Parasyte the Maxim",
  "Gurren Lagann",
  "Erased",
  "Log Horizon",
  "Steins Gate 0",
  "Full Metal Alchemist Brotherhood",
  "Angel Beats",
  "Afro Samurai",
  "Mirai Nikki (Future Diary)",
  "Tales of Borderlands",
  "Stranger Things",
  "Brooklyn 99",
  "Insatiable",
  "The Mist",
  "Lord of War",
  "Whiplash",
  "No Country for Old Men",
  "Full Metal Jacket",
  "Jojo Rabbit",
  "1917",
  "Parasyte",
  "Dragon Ball Broly",
  "Goodfellas",
  "Alita: Battle Angel",
  "Silence of the Lambs",
  "Baby Driver",
  "Inglourious Basterds",
  "Incredibles 2",
  "Deadpool 2",
  "Green Mile",
  "Shawshank Redemption",
  "Avengers (All of them)",
  "John Wick 3",
  "Black Mirror",
  "Ex Machina",
  "Bridge to Terabithia",
  "Watership Down",
  "Plague Dogs",
  "Leon the Professional",
  "The Shape of Voice",
  "Shaolin Soccer",
  "Groundhog Day",
  "Prison School",
  "All Quiet on the Western Front",
  "Oldboy",
  "I Saw the Devil",
  "Chainsaw Man",
  "The Raid: Redemption",
  "M*A*S*H",
  "Blackadder",
  "Hells Parade",
  "Heavenly Delusion",
  "Cyberpunk: Edgerunners",
  "John Wick 4",
  "Spice and Wolf",
  "Bone Tomahawk",
];

// Find missing titles from Google Sheets not in Web App
const missingFromWebApp = googleSheetsTitles.filter(
  (title) => !webAppTitles.includes(title)
);

// Find extra titles in Web App not in Google Sheets
const extraInWebApp = webAppTitles.filter(
  (title) => !googleSheetsTitles.includes(title)
);

// Output missing and extra titles
console.log("Missing from Web App:\n", missingFromWebApp.join("\n"));
console.log("\nExtra in Web App:\n", extraInWebApp.join("\n"));
